[workspace]
members = [
    "protoss",
    "protoss_derive",
    "protoss_test",
]

[patch.crates-io]
# rkyv = { path = "../rkyv/rkyv" }
rkyv = { git = "https://github.com/fu5ha/rkyv", rev = "8e558b3e3f4550c54b5eabd49a891c46c85be740"}