[package]
name = "prefix_derive"
version = "0.1.0"
authors = ["David Koloski <djkoloski@gmail.com>"]
edition = "2018"
description = "Derive macros for prefix"
license = "MIT"
documentation = "https://docs.rs/protoss"
repository = "https://github.com/djkoloski/protoss"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = "1.0"
quote = "1.0"
